### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by ousamabenyounes** [130bby/diapason#1]
Your parameters.yml file has been compromised and your login/pwd are now visible on this link:
this project
to remove it from your history:
https://help.github.com/articles/removing-sensitive-data-from-a-repository/

Change your login/pwd on all your projects...

I recommand you also to use a gitignore file on the root of your Symfony project:
https://github.com/github/gitignore/blob/master/Symfony.gitignore
This will automatically ignore your parameters.yml file, your vendors ...

I also recommand you to plug your open source symfony project to sensioInsight...It's free and help you find all security, performance or quality issue on each commit

https://insight.sensiolabs.com/

Hope this will help you :)

**Comment by 130bby** [comment]
Hello, and thanks a lot for the feedback !

I indeed made a mistake comitting some sensitive files ... (i guess that's what you get when you burn out !).

just removed it, and actually changed the compromised data. I do use a gitignore file, just wasn't carefull enough when i commited the file that i copied to the root directory. Will dig that sensioInsight you recommended.

Again, thanks for this notification and the knowledge share, good to see some white hat around !

Peace and have a great day !
